name: Update Blog Posts

on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  update-blog-posts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Update README with blog posts
      uses: gautamkrishnar/blog-post-workflow@v1
      with:
        feed_list: "https://medium.com/feed/@ravindu.nethmina.work"
        max_post_count: 5
        template: "<li>📅 {{date}} - <a href={{link}}>{{title}}</a></li>"
        date_format: "MMMM Do, YYYY"

    - name: Commit and push changes
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "ravindu.nethmina.work@gmail.com"
        git add README.md
        git commit -m "📚 Auto-update blog posts" || echo "No changes to commit"
        git push
